name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push service-a
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app:latest ./service-a
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

      # - name: Deploy to server
      #   run: |
      #     ssh -o StrictHostKeyChecking=no root@203.0.113.45 "docker pull myorg/devops-app:latest && docker restart service-a"
